### ISSUE TITLE
`display:block` negates `vertical-align`

### ISSUE THREAD

**Issue by thierryk** [jensimmons/cssremedy#76]
I believe `vertical-align` applies to (see [Formal Definition on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#formal_definition)): 

> inline-level and table-cell elements. It also applies to ::first-letter and ::first-line.

So I doubt it does anything in the rule below as it is associated with `display:block`:

```
/*
* 1. Block display is usually what we want
* 2. Remove strange space-below when inline
* 3. Responsive by default
*/
img, svg, video, canvas, audio, iframe, embed, object {
  display: block;
  vertical-align: middle;
  max-width: 100%;
}
```

`display: block` alone should take care of #2 ("Remove strange space-below when inline")

**Comment by Malvoz** [comment]
I believe `vertical-align: middle` is used here to have the gap removed irrespectively of the `display` value, in case the author changes it.

**Comment by mirisuzanne** [comment]
That's right. We decided to provide a fallback vertical-alignment as a fallback for inline use-cases, when authors override the `display` value.

**Comment by thierryk** [comment]
What about adding that piece of info to the comment then?

`* 2.  Remove strange space-below in case authors overwrite the display value`

FWIW: I didn't know this project and looking at those 2 lines made me wonder...

**Comment by mirisuzanne** [comment]
@thierryk I like that as a clarification. Do you want to make a PR?

**Comment by thierryk** [comment]
@mirisuzanne sure!

**Comment by thierryk** [comment]
PR https://github.com/jensimmons/cssremedy/pull/77 will close this
